package Calculadora;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFCalc.java
 *
 * Created on 26/02/2014, 14:46:48
 */
/**
 *
 * @author Kassiane
 */
public class JFCalc extends javax.swing.JFrame {

    char operacao;
    String temp, numero_antes,copia;
    Double num1, num2, resultado;

    /**
     * Creates new form JFCalc
     */
    public JFCalc() {
        initComponents();
    }

    private void DigitarNumero(String numero) {
        // TODO add your handling code here:
        temp = JTVisor.getText();
        numero_antes = temp;
        temp = temp + numero;
        JTVisor.setText(temp);
    }

    private void EscolherOperacao(char op) throws NumberFormatException {
        // TODO add your handling code here:
        operacao = op;
        num1 = Double.parseDouble(JTVisor.getText());
        JTVisor.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton20 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        JTVisor = new javax.swing.JTextField();
        JB2 = new javax.swing.JButton();
        JB1 = new javax.swing.JButton();
        JB4 = new javax.swing.JButton();
        JB3 = new javax.swing.JButton();
        JB6 = new javax.swing.JButton();
        JB5 = new javax.swing.JButton();
        JB8 = new javax.swing.JButton();
        JB7 = new javax.swing.JButton();
        JB9 = new javax.swing.JButton();
        JBAdicao = new javax.swing.JButton();
        JBSub = new javax.swing.JButton();
        JBMult = new javax.swing.JButton();
        JBApagar01 = new javax.swing.JButton();
        JBDivisao = new javax.swing.JButton();
        JBApagar02 = new javax.swing.JButton();
        JBIgualdade = new javax.swing.JButton();
        JB0 = new javax.swing.JButton();
        JBVirgula = new javax.swing.JButton();
        JBApagar = new javax.swing.JButton();
        JBTroca = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        jButton20.setText("jButton20");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");

        jPanel1.setBackground(new java.awt.Color(0, 204, 0));

        JTVisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTVisorActionPerformed(evt);
            }
        });

        JB2.setText("2");
        JB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB2ActionPerformed(evt);
            }
        });

        JB1.setText("1");
        JB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB1ActionPerformed(evt);
            }
        });

        JB4.setText("4");
        JB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB4ActionPerformed(evt);
            }
        });

        JB3.setText("3");
        JB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB3ActionPerformed(evt);
            }
        });

        JB6.setText("6");
        JB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB6ActionPerformed(evt);
            }
        });

        JB5.setText("5");
        JB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB5ActionPerformed(evt);
            }
        });

        JB8.setText("8");
        JB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB8ActionPerformed(evt);
            }
        });

        JB7.setText("7");
        JB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB7ActionPerformed(evt);
            }
        });

        JB9.setText("9");
        JB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB9ActionPerformed(evt);
            }
        });

        JBAdicao.setText("+");
        JBAdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAdicaoActionPerformed(evt);
            }
        });

        JBSub.setText("-");
        JBSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSubActionPerformed(evt);
            }
        });

        JBMult.setText("*");
        JBMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBMultActionPerformed(evt);
            }
        });

        JBApagar01.setText("C");
        JBApagar01.setToolTipText("Apaga todas as ações.");
        JBApagar01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBApagar01ActionPerformed(evt);
            }
        });

        JBDivisao.setText("/");
        JBDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBDivisaoActionPerformed(evt);
            }
        });

        JBApagar02.setText("CE");
        JBApagar02.setToolTipText("Apaga última ação.");
        JBApagar02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBApagar02ActionPerformed(evt);
            }
        });

        JBIgualdade.setText("=");
        JBIgualdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBIgualdadeActionPerformed(evt);
            }
        });

        JB0.setText("0");
        JB0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB0ActionPerformed(evt);
            }
        });

        JBVirgula.setText(".");
        JBVirgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBVirgulaActionPerformed(evt);
            }
        });

        JBApagar.setText("<-----");
        JBApagar.setToolTipText("Apaga último caractere.");
        JBApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBApagarActionPerformed(evt);
            }
        });

        JBTroca.setText("+ -");
        JBTroca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTrocaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(JTVisor, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JB4)
                                            .addComponent(JB7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(JB8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(JB9))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(JB5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(JB6))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(JB1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(JB2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JB3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(JB0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JBVirgula)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JBApagar02, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBApagar01, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JBApagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JBMult)
                                    .addComponent(JBDivisao)
                                    .addComponent(JBAdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBIgualdade, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JBSub)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBTroca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {JB1, JB2, JB3, JB4, JB5, JB6, JB7, JB8, JB9, JBAdicao, JBDivisao, JBMult, JBSub, JBVirgula});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {JBApagar01, JBApagar02});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTVisor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBApagar02)
                    .addComponent(JBApagar)
                    .addComponent(JBApagar01))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB1)
                    .addComponent(JB2)
                    .addComponent(JB3)
                    .addComponent(JBSub)
                    .addComponent(JBTroca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JB4)
                            .addComponent(JB5)
                            .addComponent(JB6)
                            .addComponent(JBMult))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JB7)
                            .addComponent(JB8)
                            .addComponent(JB9)
                            .addComponent(JBAdicao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBDivisao)
                            .addComponent(JB0)
                            .addComponent(JBVirgula)))
                    .addComponent(JBIgualdade, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/page.gif"))); // NOI18N
        jMenu1.setText("Calculadora");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bullet.gif"))); // NOI18N
        jMenuItem1.setMnemonic('S');
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/page_white.png"))); // NOI18N
        jMenu2.setText("Editar");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Copiar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bullet.gif"))); // NOI18N
        jMenuItem3.setText(" Colar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/reads.png"))); // NOI18N
        jMenu3.setText("Sobre");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Sair");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTVisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTVisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTVisorActionPerformed

    private void JBAdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAdicaoActionPerformed
        EscolherOperacao('+');
    }//GEN-LAST:event_JBAdicaoActionPerformed

    private void JBSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSubActionPerformed
        // TODO add your handling code here:
        EscolherOperacao('-');
    }//GEN-LAST:event_JBSubActionPerformed

    private void JBMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBMultActionPerformed
        // TODO add your handling code here:
        EscolherOperacao('*');
    }//GEN-LAST:event_JBMultActionPerformed

    private void JB9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB9ActionPerformed
        // TODO add your handling code here:
        DigitarNumero("9");
    }//GEN-LAST:event_JB9ActionPerformed

    private void JB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB8ActionPerformed
        DigitarNumero("8");
    }//GEN-LAST:event_JB8ActionPerformed

    private void JB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB7ActionPerformed
        // TODO add your handling code here
        DigitarNumero("7");
    }//GEN-LAST:event_JB7ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void JB0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB0ActionPerformed
        // TODO add your handling code here:

        DigitarNumero("0");

    }//GEN-LAST:event_JB0ActionPerformed

    private void JBApagar01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBApagar01ActionPerformed
        // TODO add your handling code here
        num1 = null;
        num2 = null;
        JTVisor.setText(null);

    }//GEN-LAST:event_JBApagar01ActionPerformed

    private void JBApagar02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBApagar02ActionPerformed
        // TODO add your handling code here:
        num2 = null;
        JTVisor.setText(String.valueOf(num1));

    }//GEN-LAST:event_JBApagar02ActionPerformed

    private void JB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB1ActionPerformed
        // TODO add your handling code here:
        DigitarNumero("1");
    }//GEN-LAST:event_JB1ActionPerformed

    private void JB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB2ActionPerformed
        // TODO add your handling code here:
        DigitarNumero("2");
    }//GEN-LAST:event_JB2ActionPerformed

    private void JB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB3ActionPerformed
        // TODO add your handling code here:
        DigitarNumero("3");
    }//GEN-LAST:event_JB3ActionPerformed

    private void JB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB4ActionPerformed
        // TODO add your handling code here:
        DigitarNumero("4");
    }//GEN-LAST:event_JB4ActionPerformed

    private void JB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB5ActionPerformed
        // TODO add your handling code here:
        DigitarNumero("5");
    }//GEN-LAST:event_JB5ActionPerformed

    private void JB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB6ActionPerformed
        // TODO add your handling code here:
        DigitarNumero("6");
    }//GEN-LAST:event_JB6ActionPerformed

    private void JBIgualdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBIgualdadeActionPerformed
        // TODO add your handling code here:
        num2 = Double.parseDouble(JTVisor.getText());

        switch (operacao) {
            case '+':
                resultado = num1 + num2;
                break;
            case '-':
                resultado = num1 - num2;
                break;
            case '*':
                resultado = num1 * num2;
                break;
            case '/':
                resultado = num1 / num2;
                break;
        }
        JTVisor.setText(String.valueOf(resultado));

    }//GEN-LAST:event_JBIgualdadeActionPerformed

    private void JBDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBDivisaoActionPerformed
        // TODO add your handling code here

        EscolherOperacao('/');
    }//GEN-LAST:event_JBDivisaoActionPerformed

    private void JBApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBApagarActionPerformed
        // TODO add your handling code here:

        temp = numero_antes;
        JTVisor.setText(temp);
    }//GEN-LAST:event_JBApagarActionPerformed

    private void JBTrocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTrocaActionPerformed
        // TODO add your handling code here:
        if (temp.startsWith("-")) {
            temp = temp.replace('-', '+');
        } else if (temp.startsWith("+")) {
            temp = temp.replace('+', '-');
        }else{
        temp = '-' + temp; 
        }
        JTVisor.setText(temp);
        
        
    }//GEN-LAST:event_JBTrocaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
        copia =JTVisor.getText();
        
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        JTVisor.setText(copia);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:

        new JFSobre().show();
    }//GEN-LAST:event_jMenu3MouseClicked

    private void JBVirgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBVirgulaActionPerformed
        // TODO add your handling code here:

        DigitarNumero(",");
    }//GEN-LAST:event_JBVirgulaActionPerformed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB0;
    private javax.swing.JButton JB1;
    private javax.swing.JButton JB2;
    private javax.swing.JButton JB3;
    private javax.swing.JButton JB4;
    private javax.swing.JButton JB5;
    private javax.swing.JButton JB6;
    private javax.swing.JButton JB7;
    private javax.swing.JButton JB8;
    private javax.swing.JButton JB9;
    private javax.swing.JButton JBAdicao;
    private javax.swing.JButton JBApagar;
    private javax.swing.JButton JBApagar01;
    private javax.swing.JButton JBApagar02;
    private javax.swing.JButton JBDivisao;
    private javax.swing.JButton JBIgualdade;
    private javax.swing.JButton JBMult;
    private javax.swing.JButton JBSub;
    private javax.swing.JButton JBTroca;
    private javax.swing.JButton JBVirgula;
    private javax.swing.JTextField JTVisor;
    private javax.swing.JButton jButton20;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
